### ISSUE TITLE
wireguard as a client, network_mode: container leaking

### ISSUE THREAD

**Issue by gaywallet** [runfalk/synology-wireguard#122]
**Description**
I set this up on on a ds920+ v7 of dsm. I'm able to connect and can verify traffic routes through wireguard

however when I use this container to route traffic via compose and network_mode: container:wireguard, things aren't working as expected. When I passed this through to a docker speedtest container (using https://github.com/henrywhitaker3/Speedtest-Tracker) it reports my isp and not the wireguard connection

I tried passing it through to a torrent program and using https://ipleak.net/ magnet link and it resolves the vpn and not my isp

however when I pass it through to a torrent and monitor traffic on my vpn's website it's clearly leaking a lot of info - was seeing maybe 1/4 of the traffic being routed

I've never had this problem with another vpn client like openvpn and using network_mode: container in compose

*wg logs*

```
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add X.X.X.X/10 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] ip -4 route add 0.0.0.0/1 dev wg0
```

*wg.conf*

```
[Interface]
Address = X.X.X.X/10
PrivateKey = 
DNS = X.X.X.X

[Peer]
PublicKey = 
PresharedKey = 
Endpoint = X.X.X.X:1637
AllowedIPs = 0.0.0.0/1
PersistentKeepalive = 15
```

*docker compose*

```
version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv6.conf.all.disable_ipv6: 0
    environment:
      TZ: 'America/Los_Angeles'
      PUID: 1026
      PGID: 101
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules:ro
      - /volume1/docker/wireguard/:/config
    ports: 
      - 51820:51820/udp
      - 8765:80
```

*relevant part of compose on other stacks*
```
network_mode: container:wireguard****
